apiVersion: v1
kind: ConfigMap
metadata:
  name: dog-01-configmap
  namespace: deviceshifu
  labels:
    app: deviceshifu-dog-01
    workspace_id: "83256708-a344-4d91-8269-50a8f0166029"
    workspace_name: "cic"
data:
  driverProperties: |
    driverSku: Robot Dog MQTT Device
    driverImage: robot-dog-mqtt:latest
---

apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-dog-01
  namespace: devices
  labels:
    app: deviceshifu-dog-01
    workspace_id: "83256708-a344-4d91-8269-50a8f0166029"
    workspace_name: "cic"
  annotations:
    workspace.id: "83256708-a344-4d91-8269-50a8f0166029"
    workspace.name: "cic"
    template.id: "robotdog-mqtt-v1"
spec:
  sku: "Robot Dog MQTT Device"
  connection: Ethernet
  address: "10.85.239.93"
  protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-dog-01
    workspace_id: "83256708-a344-4d91-8269-50a8f0166029"
  name: deviceshifu-dog-01
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-dog-01
  template:
    metadata:
      labels:
        app: deviceshifu-dog-01
        workspace_id: "83256708-a344-4d91-8269-50a8f0166029"
    spec:
      containers:
        - image: edgenesis/deeprobotics-robotdog-mqtt:v0.0.2
          name: deviceshifu-dog-01
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-dog-01"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: MQTT_BROKER_ADDRESS
              value: "10.85.238.26:1883"
            # No MQTT authentication configured in workspace
            
            - name: CONFIG_MOUNT_PATH
              value: "/etc/edgedevice/config"
            - name: DATA_FETCH_INTERVAL_SECONDS
              value: "5"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: dog-01-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-dog-01
    workspace_id: "83256708-a344-4d91-8269-50a8f0166029"
  name: deviceshifu-dog-01
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: deviceshifu-dog-01
  type: ClusterIP
